<?php
    include("sharedFunctions.php");
    function hashPassword($pass){
        $pass = password_hash($pass, PASSWORD_BCRYPT);
        //If omitted, a random salt will be generated by password_hash()
        // for each password hashed. This is the intended mode of operation.
        return $pass;
    }

    function registerUser($email, $username, $password){
        //conectare la baza de date
        $conn = mysqli_connect("localhost", "root", "", "pixData");

        //pentru siguranta
        $email = mysqli_real_escape_string($conn, $email);
        $username = mysqli_real_escape_string($conn, $username);
        $password = mysqli_real_escape_string($conn, $password);

        //pentru siguranta folosesc query-uri pregatite
        $stmt = $conn->prepare(" INSERT INTO Users(email, password) VALUES (?, ?) ");
        $stmt->bind_param("ss", $email, $password);
        $stmt->execute();
        //inchidem query-ul
        $stmt->close();
        //inchidem conexiunea la sfarsit
        mysqli_close($conn);
        header("Location: http://localhost/pixB/PiX-B/");
    }

    $username = $email = $password = "";
    if($_SERVER["REQUEST_METHOD"] == "POST") {
        if(isset($_POST["username"]) && isset($_POST["email"]) && isset($_POST["password"])) {
            $username = clearInput($_POST["username"]);
            $email = clearInput($_POST["email"]);
            $password = clearInput($_POST["password"]);
            $password = hashPassword($password);
            registerUser($email, $username, $password);
        }
        
    }


?>